export class TaskModel {
  public _id!: string; // generated by mongoDB
  public type!: string;
  public name!: string;
  public quantity!: string;
  public price!: string;
  public store!: string;
  public status!: string;
  //public where!: string;
  public createdAt!: Date; // generated by mongoDB
  constructor(model?: any) {
    Object.assign(this, model);
  }

}
