export class ShopModel {
  public _id!: string; // generated by mongoDB
  public name!: string;

  /*The products and the prices*/
  //chicken
  public chickenWhole!: number;
  public chickenBreasts!: number;
  public chickenDrums!: number;
  public chickenLegs!: number;

  //fruits
  public pineapple!: number;
  public mango!: number;
  public avocado!: number;

  //soda
  public cocaCola!: number;
  public redBull!: number;
  public gatorad!: number;

  //snacks
  public chips!: number;
  public popCorn!: number;
  public biscuits!: number;

  //bathroom
  public tootbrush!: number;
  public toothpaste!: number;
  public dentalFloss!: number;



  public createdAt!: Date; // generated by mongoDB

  constructor(model?: any) {
    Object.assign(this, model);
  }
}
